### ISSUE TITLE
Update to v5 of ALKiln

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-ALKilnSetup#222]
Update the files to push with the new version of ALKiln:
- [x] The workflow file `name` description - update the described version name.
- [x] The workflow file default version.
- [x] Update `checkout@2` to `checkout@3`
- [x] Review other files for what needs to be updated.

**Comment by BryceStevenWilley** [comment]
Looks like you did most of this in https://github.com/SuffolkLITLab/docassemble-ALKilnSetup/commit/a550c0f6f88dc74ede063e0a400e77f534b2cf4b. The only thing left is "review other files", which is kinda broad; does it need testing you think?

**Comment by plocket** [comment]
This should be good, I think. Everything could always use more testing, but I do think it's been used several times since then with no harm done. I'll close for now.
